version: '3.8'

services:
  # MongoDB para desenvolvimento local
  mongodb:
    image: mongo:7.0
    container_name: kitesurf-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: kitesurf
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - kitesurf-network

  # Mongo Express - Interface web para MongoDB (opcional)
  mongo-express:
    image: mongo-express:latest
    container_name: kitesurf-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - kitesurf-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  kitesurf-network:
    driver: bridge
